### ISSUE TITLE
Fix plot reactivity to input$norm

### ISSUE THREAD

**Issue by FrancescaMancini** [FrancescaMancini/dataxplore#10]
At the moment the plot is redrawn when the input to "norm" is changed. We need that to wait until the plot button is clicked.
This also happens in mod_species_id_bias_tab with input$type and in mod_rarity_bias_tab with input$prev and input$metric.

https://github.com/FrancescaMancini/dataxplore/blob/bc9c6171f475acaddcc48c5d3236f92a3c4aff65/R/mod_species_bias_tab.R#L51

**Comment by DylanCarbone** [comment]
Hi, this has been fixed in the latest commit using eventReactive() over observeEvent()
