### ISSUE TITLE
Add a progress bar

### ISSUE THREAD

**Issue by FrancescaMancini** [FrancescaMancini/dataxplore#11]
The plot takes a long time to appear as `assessRarityBias()` can take a long time to run with large datasets. We should add a progress bar or something similar so the user doesn't keep changing inputs or click the plot button multiple times.

https://github.com/FrancescaMancini/dataxplore/blob/bc9c6171f475acaddcc48c5d3236f92a3c4aff65/R/mod_rarity_bias_tab.R#L181

**Comment by DylanCarbone** [comment]
I've made a basic progress bar in the latest commit. It's a bit rudimentary because it cannot measure progress within the assessRarityBias() function, however, it does notify users that the plot is loading it's just taking some time.
