### ISSUE TITLE
Let user specify date format

### ISSUE THREAD

**Issue by FrancescaMancini** [FrancescaMancini/dataxplore#2]
https://github.com/FrancescaMancini/dataxplore/blob/6ca40fd5bec810a28c095ddf3b36c40332f001be/R/mod_data_tab.R#L114-L124

The user could supply the dates in a number of different formats. At the moment the date summary functionality only works if the format is "%d/%m/%Y". We need to let the user specify the format and then use that input to format the variable as date. It's probably best to do this in the main app UI and server functions (like for the grid references conversion) so the updated data object is available to all modules and then modify the code in mod_data_tab.R accordingly.

**Comment by DylanCarbone** [comment]
I've added an option for the user to specify the date format in the commit baf5ed993df13c352bbd1008d9d7fba0b117f429

Next I'll extract the year and make the data object available to the other modules

**Comment by DylanCarbone** [comment]
Year is extracted from the user's date selection
