### ISSUE TITLE
Extract year from date

### ISSUE THREAD

**Issue by FrancescaMancini** [FrancescaMancini/dataxplore#3]
The user's dataset might not have a "year" column but only a "date" one. It might be nice to give the user the option to create that "year" column within the app. It would be best to add this code to the main app UI and server functions so the updated data object is available to all modules. This is linked to #2 .

**Comment by DylanCarbone** [comment]
I've made it so that the user specifies the date column, and year is automatically extracted from the date. Although, it would be best if the user can specify whether they have recorded the year or whether they have recorded date, so that the app can accept both options. I'll add this

**Comment by DylanCarbone** [comment]
actually I think we should just have the date column option. I can't foresee users not recording the date.
