### ISSUE TITLE
Fix species, latitude and longitude columns

### ISSUE THREAD

**Issue by FrancescaMancini** [FrancescaMancini/dataxplore#6]
At the moment the user has to enter the column names to pass to the function arguments in every tab. This does allow some flexibility in exploring the data lots of different ways in each tab, but it can also be annoying having to enter the same information multiple time. 
We can safely assume that the species, latitude and longitude columns are not likely to change so we can keep those fixed so the user does not have to specify them in every tab.

**Comment by DylanCarbone** [comment]
Hi @FrancescaMancini 

Can we also assume that date and year (which I will extract from date) will be unchanged?

Thanks,

Dylan

**Comment by FrancescaMancini** [comment]
Yes I think that is reasonable.

**Comment by DylanCarbone** [comment]
The formatted table is now available in a formatted_data() object
