### ISSUE TITLE
species bias tab crashes when periodtype = ranges

### ISSUE THREAD

**Issue by FrancescaMancini** [FrancescaMancini/dataxplore#9]
When trying to specify periods as ranges in the [species bias tab](https://github.com/FrancescaMancini/dataxplore/blob/master/R/mod_species_bias_tab.R) the app crashes with error

`Warning: Error in seq.default: 'from' must be of length 1`

**Comment by FrancescaMancini** [comment]
Same happens in mod_species_id_bias_tab and mod_rarity_bias_tab

**Comment by DylanCarbone** [comment]
I think this has been fixed, as I nolonger encounter this error
